CRYPTO_PAIRS = {
    "ADA/USD": "ADA-USD",
    "ALGO/USD": "ALGO-USD",
    "ATOM/USD": "ATOM-USD",
    "AVAX/USD": "AVAX-USD",
    "BCH/USD": "BCH-USD",
    "BNB/USD": "BNB-USD",
    "BTC/USD": "BTC-USD",
    "DOGE/USD": "DOGE-USD",
    "DOT/USD": "DOT-USD",
    "ETH/USD": "ETH-USD",
    "FIL/USD": "FIL-USD",
    "HBAR/USD": "HBAR-USD",
    "LEO/USD": "LEO-USD",
    "LINK/USD": "LINK-USD",
    "LTC/USD": "LTC-USD",
    "NEAR/USD": "NEAR-USD",
    "SHIB/USD": "SHIB-USD",
    "SOL/USD": "SOL-USD",
    "TON/USD": "TON11419-USD",
    "TRX/USD": "TRX-USD",
    "UNI/USD": "UNI7083-USD",
    "XLM/USD": "XLM-USD",
    "XMR/USD": "XMR-USD",
    "XRP/USD": "XRP-USD",
    "ZEC/USD": "ZEC-USD",
}